jobs:
 build:
   machine: true
   steps:
     - checkout
     # build
     - run: make all
     # cleanup
     - run: make clean
     - run: 
        name: "get ghr"
        command: |
         GHR_VERSION=0.13.0
         GHR_URL=https://github.com/tcnksm/ghr/releases/download/v${GHR_VERSION}/ghr_v${GHR_VERSION}_linux_amd64.tar.gz
         wget "$GHR_URL" && \
         tar xzf ghr_v${GHR_VERSION}_linux_amd64.tar.gz && \
         sudo mv ghr_v${GHR_VERSION}_linux_amd64/ghr /usr/bin/ghr && \
         sudo rm -r ghr_v${GHR_VERSION}_linux_amd64.tar.gz ghr_v${GHR_VERSION}_linux_amd64/
     - run:
        name: "Publish Release on GitHub"
        command: |
         VERSION=$(date +'%y%m%d'00)
         ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} ~/project/Devuan.zip

workflows:
 version: 2
 main:
  jobs:
   - build:
      filters:
       tags:
        ignore: /.*/
