name: "DevuanWSL Build"

on:
  push:
    branches: [ daedalus ]
    # Trigger only when Makefile is changed
    paths: ['Makefile']
  workflow_dispatch:
  schedule:
    # Trigger every Tuesday at 23:50 UTC
    - cron: "50 23 * * tue"

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip build with [ci skip] in commit
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: 'daedalus'
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - run: mkdir -p release
      - name: install dependencies
        run: sudo apt install -y curl libarchive-tools jq tar unzip xz-utils
      - name: build package & make hash
        run: |
             sudo make
             sudo make clean
             sha512sum Devuan.zip > Devuan.zip.sha512
             mv Devuan.zip* release/
      - name: save release as artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 10
          name: Devuan-packed.zip
          path: release
      - name: upload artifact to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          prerelease: True
          tag: "action-build"
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          artifacts: "release/Devuan.zip*"
          token: ${{ secrets.GITHUB_TOKEN }}
