name: "DevuanWSL Nightly Release"

on:
  push:
    branches: [ chimaera ]
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
            - info
            - warning
            - debug
  #schedule:
    # Trigger every day at 23:50 UTC
  #  - cron: "50 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: 'chimaera'
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - run: mkdir -p release
      - name: install dependencies
        run: sudo apt install -y curl libarchive-tools jq tar unzip wget
      - name: build package
        run: sudo make && sudo make clean
      - name: save release as artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 7
          name: Devuan.zip
          path: release
    
